#!/bin/sh

# mktempfifo: create a temporary named file, print its name
#
# template
#	Specify a template for the named file. It must contain at
#	least 6 consecutive 'X's in last component. If template
#	is not specified, use \$TMPDIR/tmpfifo.XXXXXXXXXX. If
#	\$TMPDIR is unset or null, then use /tmp.

IFS=' 	
'
syspath=$(command -p getconf PATH 2>/dev/null)
PATH="${syspath:-/bin:/usr/bin}${PATH:+:$PATH}"
progname=$(basename "$0")

usage() {
	printf 'usage: %s [template]\n' "$progname" >&2
	exit 1
}

fatal() {
	printf '%s: %s\n' "$progname" "$1" 1>&2
	exit ${2:-1}
}

_mktempfifo() (
	export LANG=C
	export LC_ALL=C
	[ -r /dev/urandom ] || return 1

	tempchar='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
	TMPDIR=${TMPDIR:-/tmp}
	template=${1:-"${TMPDIR%/}/tmpfifo.XXXXXXXXXX"}
	prefix=$(printf '%s\n' "$template" | sed 's/X*$//')
	numX=$((${#template} - ${#prefix}))
	[ "$numX" -ge 6 ] || return 1

	# try 10 times
	for i in 1 2 3 4 5 6 7 8 9 10
	do
		suffix=$(tr -dc  "$tempchar" < /dev/urandom |
			dd bs="$numX" count=1 2>/dev/null)
		tempfifo="${prefix}${suffix}"
		mkfifo -m 0600 "$tempfifo" 1>&2
		if [ $? -eq 0 ]
		then
			printf '%s\n' "$tempfifo"
			return 0
		fi
	done
	return 1
)

while getopts h opt; do
	case "$opt" in
	h|?) usage;;
	esac
done
shift $((OPTIND-1))

_mktempfifo ${1+"$1"} || fatal 'cannot create temporary named pipe' $?
