#!/bin/sh

usage() {
	echo 'usage: walkf [-i] [-l] [DIR..]' >&2
	exit 1
}

fatal() {
	echo "walkf: $*" >&2
	exit 1
}

if ! type walk >/dev/null 2>&1
then
	fatal 'not found walk'
fi

unset iflag lflag
while getopts ilh opt
do
	case "$opt" in
	i)   iflag=-i;;
	l)   lflag="true";;
	h|?) usage;;
	esac
done
shift $((OPTIND-1))

walk -l $iflag "$@" \
	| awk -v lflag="$lflag" '
	$1 !~ /[dLDpS?]/ {
		if (lflag == "true") {
			print
		} else {
			for (i = 7; i <= NF; i++)
				printf("%s", $i)
			print ""
		}
	}'
